#!/bin/bash
## aliases
## aliases for slack 
## version 0.0.1 - initial
##################################################
shopt -s expand_aliases
#-------------------------------------------------
alias setup-user-channel-history='
{
  local user_channel_history
  user_channel_history=$( 
    get-user-channels-history ${member_id} 
  )
}
'
#-------------------------------------------------
alias for-each-channel-get-user-channel-history-payload-on-empty-channel=' 
{ 
  slack-channels-history-empty || {
    {
      cecho white empty channel history 
      cecho white next
    } 1>&2
    continue
  }
}
'
#-------------------------------------------------
alias for-each-channel-get-user-channel-history-payload-on-empty-user-channel='
{
  test "${user_channel_history}" || {
    {
      cecho white empty user channel history 
      cecho white next
    } 1>&2
    continue
  }
}
'
#-------------------------------------------------
alias setup-global-user-channel-history='
{
  local user_channel_history 
  user_channel_history=$( 
   for-each-channel-get-user-channel-history \
   | tee ${cache}/temp-user-channel-history
  )
}
'
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 20:49:10 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
