#!/bin/bash
## functions-channels
## - functions for channels
## version 0.0.1 - initial
##################################################
slack-channels-history-if-oldest-ts() { 
 test ! "${oldest_ts}" || {
  echo "&oldest=$( ${oldest_ts} )"
 }
}
#-------------------------------------------------
slack-channels-history-if-oldest-date() { 
 test ! "${arg_oldest_date}" || {
  echo "&oldest=$( ts-date ${arg_oldest_date} )"
 }
}
#-------------------------------------------------
slack-channels-history-if-oldest() { 
 ${FUNCNAME}-ts
 ${FUNCNAME}-date
}
#-------------------------------------------------
slack-channels-history-empty-query() { 
  {
    cat ${cache}/temp-slack-channels-history \
    | jq '.messages|length'
  }
}
#-------------------------------------------------
slack-channels-history-empty() { 
 test ! $( ${FUNCNAME}-query ) -eq 0
}

#-------------------------------------------------
slack-channels() {
 commands
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 21:26:58 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
