#!/bin/bash
## functions
## - slack.sh function
## version 0.1.2 - migrate command, error to sh2
##################################################
# version 0.0.3 - case all cecho starting
setup-channel-ids() {
 cecho green in ${FUNCNAME}
 test ! "${channel_ids}" = "all" || {
  cecho green getting all channel ids..
  channel_ids=$( 
   get-channel-ids | sed-strip-double-quotes
  )
 }
 cecho yellow channel_ids: ${channel_ids}
}
#-------------------------------------------------
escape-slash() {
  {
    echo ${@} 
  } | sed-escape-slash
}
#-------------------------------------------------
floor() {
 echo ${@} \
 | sed -e 's/[.]*$//'
}
#-------------------------------------------------
trim() {
 echo ${@} \
 | sed -e 's/"//g'
}
#-------------------------------------------------
get-user-channel-history-ts() {
 echo ${user_channel_history} \
 | jq '.["ts"]' 
}
#-------------------------------------------------
# version 0.0.2 - using channel_ids
for-each-channel-get-user-channel-history-payload() { 

 local channel
 for channel in ${channel_ids}
 do

  cecho yellow channel: ${channel} 1>&2 

  { # initialize channel history
    slack-channels-history ${date_oldest} # > temp-slack-channels-history
  } 1>/dev/null

  for-each-channel-get-user-channel-history-payload-on-empty-channel # continue on empty channel history

  ## test has more true case 

  cecho yellow member_ids: ${member_ids}
 
  local member_id
  for member_id in ${member_ids}
  do

   cecho yellow member_id: ${member_id} 1>&2

   setup-user-channel-history # ${user_channel_history} > temp-get-user-channels-history
   
   for-each-channel-get-user-channel-history-payload-on-empty-user-channel # continue on empty user channel history

   echo ${user_channel_history} | jq '.' 

  done

 done 

}
#-------------------------------------------------
# version 0.0.2 - caching
for-each-channel-get-user-channel-history() {
  cecho green [ begin ${FUNCNAME}
  {
    #cache \
    #"${cache}/${FUNCNAME}" \
    "${FUNCNAME}-payload"
  }

  cecho green end of ${FUNCNAME} ]
}
#-------------------------------------------------
# for-each-channel
# - do something on each channel
# + currently fectching user channel history
# version 0.0.5 - inherit channel ids
#-------------------------------------------------
method-slug() { { local candidate_method ; candidate_method="${1}" ; }
 echo ${candidate_method} | sed -e 's/[.]/-/g'
}
#-------------------------------------------------
get-member-id() { { local candidate_name ; candidate_name=${@} ; }

 test ! "$( get-member-id-by-real-name ${candidate_name} )" || {
  get-member-id-by-real-name "${candidate_name}" 
  return
 }

 test ! "$( get-member-id-by-profile-display-name ${candidate_name} )" || {
  get-member-id-by-profile-display-name "${candidate_name}"
  return
 }

}
#-------------------------------------------------
slack-query() { { local api_method ; api_method="${1}" ; local queary ; query="${2}" ; }
  test "${api_method}" 
  test "${query}" || {
   error "query not specified" "${FUNCNAME}" "${LINENO}"
   false
  }
  local input_json
  input_json="${cache}/temp-slack-$( method-slug ${api_method} )"
  test ! -f "${input_json}" || {
    {
      cat ${input_json} | jq "${query}" 
    }
  }
}
#-------------------------------------------------
slack-users() {
 commands
}
##################################################
## generated by create-stub2.sh v0.1.0
## on Tue, 17 Apr 2018 23:11:12 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
