#!/bin/bash
## functions-entry
## - functios for slack/entry
## version 0.0.1 - initial
##################################################
#-------------------------------------------------
slack_api_token=
channel=
member_ids=
output_format=
slack-initialize-output-format() {
 test "${output_format}" && {
  test ! "${debug}" = "true" || {
   cecho green using config output_format "'${output_format}'"
  }
 true
 } || {
 test -f "set-output" && {
  output_format=$( cat set-output )
 true
 } || {
  output_format="json"
 }
 }
}
debug=
slack-initialize-debug() {
 test "${debug}" && { 
  test ! "${debug}" = "true" || {
   cecho green using config debug "'${debug}'"
  }
 true
 } || {
 test -f "set-debug" && {
  debug=$( cat set-debug )
 true 
 } || {
  debug="false"
 }
 }
}
#-------------------------------------------------
# version 0.0.2 - handdle missing config
slack-initialize-config() {
 test -f "$( dirname ${0} )/slack-config.sh" || {
  error "missing slack-config.sh" "" ""
  false
 }
 . $( dirname ${0} )/slack-config.sh
}
#-------------------------------------------------
slack-initialize() {
 ${FUNCNAME}-config
 ${FUNCNAME}-output-format 
 ${FUNCNAME}-debug
}
#-------------------------------------------------
slack() {
 ${FUNCNAME}-initialize
 {
   ${FUNCNAME}-channels-history
   ${FUNCNAME}-channels-list
   ${FUNCNAME}-users-list
 } 1>/dev/null
 commands
}
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 21:29:46 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
