#!/bin/bash
## header
## =stub=
## version 0.0.1 - initial
##################################################
test ${#} -eq 1 && {
 slack_source_path="${1}"
true
} || {
 slack_source_path=$( dirname ${0} )
}
. ${slack_source_path}/sh2/header.sh ${slack_source_path}/sh2
. ${slack_source_path}/aliases/sed.sh
. ${slack_source_path}/aliases.sh
. ${slack_source_path}/functions.sh
. ${slack_source_path}/functions-api.sh 
. ${slack_source_path}/functions-test.sh 
. ${slack_source_path}/functions-for-each-channel.sh 
. ${slack_source_path}/functions-channels.sh 
. ${slack_source_path}/functions-ts.sh 
. ${slack_source_path}/functions-entry.sh 
unset slack_source_path
##################################################
## generated by create-stub2.sh v0.1.1
## on Mon, 07 May 2018 10:37:17 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
