#!/bin/bash
## shed
## - export workdspace slack history
## version 0.0.1 - initial
## requires:
## - slack.sh
##################################################
. $( dirname ${0} )/slack.sh &>/dev/null
##################################################
slack-shed-date-oldest() { { local date_oldest ; date_oldest="${1}" ; }
  {
    for-each-channel ${date_oldest}
  } 2>/dev/null
}
#-------------------------------------------------
slack-shed-help() {
 cat << EOF
slack-shed

OPTIONS

	date-oldest yyyy-mm-dd

	- get channel histories between now and oldest date

EOF
}
#-------------------------------------------------
slack-shed() { 
 commands
}
#-------------------------------------------------
shed() {
 slack shed ${@}
}
##################################################
if [ ! ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
shed ${@}
##################################################
## generated by create-stub2.sh v0.1.0
## on Mon, 09 Apr 2018 20:05:08 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
