#!/bin/bash
## slack
## - slack api
## version 0.0.5 - export functions
## by <https://github.com/temptemp3>
## see <https://github.com/temptemp3/slack.sh>
## requires:
## - jq
##################################################
. $( dirname ${0} )/functions.sh
##################################################
if [ ! ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
slack ${@}
##################################################
## generated by create-stub2.sh v0.1.0
## on Sat, 31 Mar 2018 15:22:33 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
