#!/bin/bash
## slack
## - slack api
## version 0.1.1 - using header
##################################################
. $( dirname ${0} )/header.sh $( dirname ${0} )
##################################################
if [ ! ]
then
 true
else
 exit 1 # wrong args
fi
##################################################
slack ${@}
##################################################
## generated by create-stub2.sh v0.1.0
## on Sat, 31 Mar 2018 15:22:33 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
