#!/bin/bash
## aliases/sed
## version 0.0.1 - testing integration
##################################################
shopt -s expand_aliases
alias sed-strip-double-quotes='sed -e "s/\"//g"'
alias sed-escape-slash='sed -e "s/\([/]\)/\\\\\1/g"'
##################################################
## generated by create-stub2.sh v0.1.1
## on Sun, 06 May 2018 15:42:39 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
